/**
 * This script converts tokens from colour-token.json and design-tokens.tokens.json
 * into CSS custom properties (variables) and saves them in tokens/design-tokens.css.
 */

const fs = require('fs');
const path = require('path');

// Paths to files
const colorTokensPath = path.join(__dirname, 'colour-token.json');
const designTokensPath = path.join(__dirname, 'design-tokens.tokens.json');
const outputPath = path.join(__dirname, 'design-tokens.css');

// MD3 standard error palette
const errorPalette = {
  "0": "hsl(0, 0%, 0%)",
  "10": "hsl(358, 100%, 13%)",
  "20": "hsl(357, 100%, 21%)",
  "30": "hsl(356, 100%, 29%)",
  "40": "hsl(0, 75%, 42%)",
  "50": "hsl(2, 73%, 53%)",
  "60": "hsl(4, 100%, 64%)",
  "70": "hsl(6, 100%, 74%)",
  "80": "hsl(6, 100%, 83%)",
  "87": "hsl(7, 100%, 88%)",
  "90": "hsl(6, 100%, 92%)",
  "92": "hsl(9, 100%, 96%)",
  "94": "hsl(10, 100%, 96%)",
  "95": "hsl(9, 100%, 96%)",
  "96": "hsl(9, 100%, 97%)",
  "98": "hsl(280, 100%, 99%)",
  "99": "hsl(280, 100%, 99%)",
  "100": "hsl(0, 0%, 100%)"
};

// Programmatic fallback for missing neutral shades needed in dark mode
const missingNeutralPalette = {
  "4": "hsl(270, 7%, 4%)",
  "6": "hsl(270, 7%, 6%)",
  "12": "hsl(270, 7%, 12%)",
  "17": "hsl(276, 5%, 17%)",
  "22": "hsl(276, 5%, 22%)",
  "24": "hsl(276, 5%, 24%)"
};


function main() {
  try {
    // Read JSON files
    const colorTokens = JSON.parse(fs.readFileSync(colorTokensPath, 'utf8'));
    const designTokens = JSON.parse(fs.readFileSync(designTokensPath, 'utf8'));

    const cssLines = [];
    cssLines.push('/* This file is auto-generated by convert-tokens.js. Do not edit directly. */\n');

    // 1. Convert Typography
    cssLines.push(':root {');
    cssLines.push('  /* ==========================================================================');
    cssLines.push('     Typography Variables');
    cssLines.push('     ========================================================================== */');

    const typography = designTokens.typography;
    if (typography) {
      for (const [roleName, properties] of Object.entries(typography)) {
        const kebabRole = roleName.replace(/\s+/g, '-');
        
        const fsVal = properties.fontSize ? properties.fontSize.value : null;
        const ffVal = properties.fontFamily ? properties.fontFamily.value : null;
        const fwVal = properties.fontWeight ? properties.fontWeight.value : null;
        const lsVal = properties.letterSpacing ? properties.letterSpacing.value : null;
        const lhVal = properties.lineHeight ? properties.lineHeight.value : null;

        if (fsVal !== null) {
          cssLines.push(`  --typo-${kebabRole}-font-size: ${fsVal}px;`);
        }
        if (ffVal !== null) {
          const ffFormatted = ffVal.includes(' ') ? `'${ffVal}'` : ffVal;
          cssLines.push(`  --typo-${kebabRole}-font-family: ${ffFormatted};`);
        }
        if (fwVal !== null) {
          cssLines.push(`  --typo-${kebabRole}-font-weight: ${fwVal};`);
        }
        if (lsVal !== null) {
          cssLines.push(`  --typo-${kebabRole}-letter-spacing: ${lsVal}px;`);
        }
        if (lhVal !== null) {
          cssLines.push(`  --typo-${kebabRole}-line-height: ${lhVal}px;`);
        }
      }
    }
    cssLines.push('');
    // 1.5. Add Border Radius
    cssLines.push('');
    cssLines.push('  /* ==========================================================================');
    cssLines.push('     Border Radius');
    cssLines.push('     ========================================================================== */');
    cssLines.push('  --radius-sm: 4px;');
    cssLines.push('  --radius-md: 8px;');
    cssLines.push('  --radius-lg: 12px;');

    // 2. Convert Color Roles
    // Helper to resolve color references recursively
    function resolveColor(value) {
      if (typeof value !== 'string') return value;

      const match = value.match(/^\{([^}]+)\}$/);
      if (!match) return value;

      const pathParts = match[1].split('.');

      // Resolve from the custom error palette if it refers to error palette
      if (pathParts[0] === 'color' && pathParts[1] === 'palette' && pathParts[2] === 'error') {
        const shade = pathParts[3];
        if (errorPalette[shade]) {
          return errorPalette[shade];
        }
      }

      // Resolve missing neutral shades if they refer to neutral palette
      if (pathParts[0] === 'color' && pathParts[1] === 'palette' && pathParts[2] === 'neutral') {
        const shade = pathParts[3];
        if (colorTokens.color && colorTokens.color.palette && colorTokens.color.palette.neutral) {
          if (!colorTokens.color.palette.neutral[shade] && missingNeutralPalette[shade]) {
            return missingNeutralPalette[shade];
          }
        }
      }

      // Traversal of colour-token.json structure
      let current = colorTokens;
      for (const part of pathParts) {
        if (current === undefined || current === null) break;
        current = current[part];
      }

      if (current !== undefined && current !== null) {
        return resolveColor(current);
      }

      return value;
    }

    // Helper to convert camelCase to kebab-case
    function camelToKebab(str) {
      return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
    }

    const roles = colorTokens.color ? colorTokens.color.role : null;
    if (roles) {
      // Light theme colors inside :root
      cssLines.push('  /* ==========================================================================');
      cssLines.push('     Light Theme Color Roles');
      cssLines.push('     ========================================================================== */');
      
      const lightRoles = roles.light || {};
      for (const [roleName, value] of Object.entries(lightRoles)) {
        const kebabRole = camelToKebab(roleName);
        const resolvedValue = resolveColor(value);
        cssLines.push(`  --color-${kebabRole}: ${resolvedValue};`);
      }
      cssLines.push('}\n');

      // Dark theme colors inside [data-theme="dark"]
      cssLines.push('[data-theme="dark"] {');
      cssLines.push('  /* ==========================================================================');
      cssLines.push('     Dark Theme Color Roles');
      cssLines.push('     ========================================================================== */');
      
      const darkRoles = roles.dark || {};
      for (const [roleName, value] of Object.entries(darkRoles)) {
        const kebabRole = camelToKebab(roleName);
        const resolvedValue = resolveColor(value);
        cssLines.push(`  --color-${kebabRole}: ${resolvedValue};`);
      }
      cssLines.push('}');
    } else {
      cssLines.push('}');
    }

    // Write output to design-tokens.css
    fs.writeFileSync(outputPath, cssLines.join('\n') + '\n', 'utf8');
    console.log(`Successfully generated design-tokens.css at ${outputPath}`);
  } catch (error) {
    console.error('Error converting tokens:', error);
    process.exit(1);
  }
}

main();
